# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python: 3.5

env:
  - TOXENV=py35
  - TOXENV=py34
  # A recent Travis update broke Python 3.3
  # - TOXENV=py33
  - TOXENV=py27
  # - TOXENV=py26
  # - TOXENV=pypy

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox

# command to run tests, e.g. python setup.py test
script: tox

